// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function resolveSupabaseCredentials() {
  let rawUrl = (import.meta.env.VITE_SUPABASE_URL as string || '').trim();
  let rawKey = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string || '').trim();
  const projectId = (import.meta.env.VITE_SUPABASE_PROJECT_ID as string || 'lyhnvcpkxbbafewkzgjo').trim();

  // Handle case where URL and Key were swapped in environment configuration
  if (rawUrl.startsWith('ey') && (rawKey.startsWith('http') || !rawUrl.startsWith('http'))) {
    const temp = rawUrl;
    rawUrl = rawKey;
    rawKey = temp;
  }

  // Ensure URL is a valid HTTP/HTTPS URL
  let finalUrl = rawUrl;
  if (!/^https?:\/\//i.test(finalUrl)) {
    if (projectId && !projectId.startsWith('MY_') && !projectId.startsWith('ey')) {
      finalUrl = `https://${projectId}.supabase.co`;
    } else {
      finalUrl = 'https://lyhnvcpkxbbafewkzgjo.supabase.co';
    }
  }

  // Ensure Key is a valid token string
  let finalKey = rawKey;
  if (!finalKey || finalKey.startsWith('http') || finalKey.startsWith('MY_')) {
    finalKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5aG52Y3BreGJiYWZld2t6Z2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMDUxODUsImV4cCI6MjA5MjU4MTE4NX0.v1ZHwcIvuIHe1ygiJDhVyifKmkn88l7e-tKx58iMxnY';
  }

  return { url: finalUrl, key: finalKey };
}

const credentials = resolveSupabaseCredentials();

export const SUPABASE_URL = credentials.url;
export const SUPABASE_PUBLISHABLE_KEY = credentials.key;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});